CREATE CONSTRAINT FOR (u:User) REQUIRE u.user_id IS UNIQUE;

CREATE CONSTRAINT FOR (o:Order) REQUIRE o.order_id IS UNIQUE;

CREATE CONSTRAINT FOR (p:Product) REQUIRE p.product_id IS UNIQUE;

CREATE CONSTRAINT FOR (c:Category) REQUIRE c.category_id IS UNIQUE;

